/* Generated by scripts/gen_params.py — DO NOT EDIT BY HAND.
 *
 * module.json is capped at 8 KB by Schwung's loader, so chain_params and the
 * page hierarchy are served dynamically from the DSP via get_param().
 *
 * The pot and enum tables below define storage order for the state blob.
 * Appending is safe; reordering breaks every saved patch.
 */
#ifndef SD606_PARAMS_H
#define SD606_PARAMS_H

typedef enum { SD606_LIN = 0, SD606_EXP = 1 } sd606_curve_t;

typedef struct {
    const char   *key;
    float         min;
    float         max;
    sd606_curve_t curve;
    int           def;      /* default POT position, 0..127 */
} sd606_pot_t;

typedef struct {
    const char *key;
    int         count;      /* number of options */
    int         def;
} sd606_enum_t;

#define SD606_NUM_POTS  40
#define SD606_NUM_ENUMS 11

static const sd606_pot_t g_sd606_pots[SD606_NUM_POTS] = {
    { "bd_tune",    -9.7800f,    14.2200f, SD606_LIN,  64 },
    { "bd_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "bd_attack",     0.0000f,     1.0000f, SD606_LIN,  38 },
    { "bd_drift",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "bd_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "bd_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "sd_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "sd_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "sd_snappy",     0.0000f,     1.0000f, SD606_LIN,  95 },
    { "sd_tone",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "sd_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "sd_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "lt_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "lt_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "lt_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "lt_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "ht_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "ht_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "ht_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "ht_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "ch_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "ch_decay",     0.0000f,     1.0000f, SD606_LIN,  89 },
    { "ch_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "ch_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "oh_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "oh_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "oh_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "oh_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "cy_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "cy_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "cy_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "cy_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "cp_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "cp_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "cp_noise",     0.0000f,     1.0000f, SD606_LIN,  64 },
    { "cp_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "cp_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "master_drive",     0.2000f,     8.0000f, SD606_EXP,  55 },
    { "volume",     0.0000f,     1.0000f, SD606_LIN,  76 },
    { "accent",     1.0000f,     4.0000f, SD606_LIN,  42 },
};

static const sd606_enum_t g_sd606_enums[SD606_NUM_ENUMS] = {
    { "bd_dist_type",  4,  0 },
    { "sd_dist_type",  4,  0 },
    { "lt_dist_type",  4,  0 },
    { "ht_dist_type",  4,  0 },
    { "ch_dist_type",  4,  0 },
    { "hh_choke",  3,  1 },
    { "oh_dist_type",  4,  0 },
    { "cy_dist_type",  4,  0 },
    { "cp_dist_type",  4,  0 },
    { "master_dist",  5,  0 },
    { "note_map",  2,  0 },
};

#define SD606_CHAIN_PARAMS_LEN 4019
static const char sd606_chain_params_json[] =
    "[{\"key\":\"bd_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"bd_decay\",\"name\":\"Decay\",\"ty"
    "pe\":\"int\",\"min\":0,\"max\":127},{\"key\":\"bd_attack\",\"name\":\"Attack\",\"type\":\"int\",\"min\":0,\"max\":127,\"viz\""
    ":false},{\"key\":\"bd_drift\",\"name\":\"Drift\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"bd_drive\",\"name\":\"D"
    "rive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"bd_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"optio"
    "ns\":[\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"bd_level\",\"name\":\"Level\",\"type\":\"int\",\"mi"
    "n\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"sd_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127"
    "},{\"key\":\"sd_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"sd_snappy\",\"name\":\"Snappy"
    "\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"sd_tone\",\"name\":\"Tone\",\"type\":\"int\",\"min\":0,\"max\":127},{\"k"
    "ey\":\"sd_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"sd_dist_type\",\"name\":\"Distorti"
    "on\",\"type\":\"enum\",\"options\":[\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"sd_level\",\"name\":"
    "\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"lt_tune\",\"name\":\"Tune\",\"type\""
    ":\"int\",\"min\":0,\"max\":127},{\"key\":\"lt_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"l"
    "t_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"lt_dist_type\",\"name\":\"Distortion\",\"t"
    "ype\":\"enum\",\"options\":[\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"lt_level\",\"name\":\"Level"
    "\",\"type\":\"int\",\"min\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ht_tune\",\"name\":\"Tune\",\"type\":\"int\""
    ",\"min\":0,\"max\":127},{\"key\":\"ht_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"ht_driv"
    "e\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"ht_dist_type\",\"name\":\"Distortion\",\"type\":\""
    "enum\",\"options\":[\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"ht_level\",\"name\":\"Level\",\"typ"
    "e\":\"int\",\"min\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ch_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\""
    ":0,\"max\":127},{\"key\":\"ch_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"ch_drive\",\"na"
    "me\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"ch_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\","
    "\"options\":[\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"ch_level\",\"name\":\"Level\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"hh_choke\",\"name\":\"Choke\",\"type\":\"enum\",\"options"
    "\":[\"Off\",\"CH > OH\",\"Mutual\"]},{\"key\":\"oh_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":"
    "\"oh_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"oh_drive\",\"name\":\"Drive\",\"type\":\"i"
    "nt\",\"min\":0,\"max\":127},{\"key\":\"oh_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"H"
    "ard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"oh_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,"
    "\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cy_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"cy_de"
    "cay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"cy_drive\",\"name\":\"Drive\",\"type\":\"int\",\"m"
    "in\":0,\"max\":127},{\"key\":\"cy_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Hard Cl"
    "ip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"cy_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"viz\":"
    "{\"kind\":\"fader\"}},{\"key\":\"cp_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"cp_decay\",\""
    "name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"cp_noise\",\"name\":\"Noise\",\"type\":\"int\",\"min\":0,"
    "\"max\":127},{\"key\":\"cp_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"cp_dist_type\",\"n"
    "ame\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"key\":\"cp_"
    "level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"master_dist\",\"n"
    "ame\":\"Master Dist\",\"type\":\"enum\",\"options\":[\"Off\",\"Diode\",\"Hard Clip\",\"Wavefolder\",\"Bitcrush\"]},{\"ke"
    "y\":\"master_drive\",\"name\":\"Master Drive\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"volume\",\"name\":\"Volu"
    "me\",\"type\":\"int\",\"min\":0,\"max\":127,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"accent\",\"name\":\"Accent\",\"type\":\"i"
    "nt\",\"min\":0,\"max\":127},{\"key\":\"note_map\",\"name\":\"Note Map\",\"type\":\"enum\",\"options\":[\"Drum Rack (36+)"
    "\",\"General MIDI\"]}]";

#define SD606_UI_PAGES_LEN 3102
static const char sd606_ui_pages_json[] =
    "{\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"knobs\":[\"bd_tune\",\"bd_decay\",\"bd_attack\",\"bd_drift\",\"bd_drive\","
    "\"bd_dist_type\",\"bd_level\"],\"params\":[{\"key\":\"bd_tune\",\"name\":\"Tune\"},{\"key\":\"bd_decay\",\"name\":\"Decay"
    "\"},{\"key\":\"bd_attack\",\"name\":\"Attack\"},{\"key\":\"bd_drift\",\"name\":\"Drift\"},{\"key\":\"bd_drive\",\"name\":\"D"
    "rive\"},{\"key\":\"bd_dist_type\",\"name\":\"Distortion\"},{\"key\":\"bd_level\",\"name\":\"Level\"}]},\"sd\":{\"name\":\""
    "Snare\",\"knobs\":[\"sd_tune\",\"sd_decay\",\"sd_snappy\",\"sd_tone\",\"sd_drive\",\"sd_dist_type\",\"sd_level\"],\"pa"
    "rams\":[{\"key\":\"sd_tune\",\"name\":\"Tune\"},{\"key\":\"sd_decay\",\"name\":\"Decay\"},{\"key\":\"sd_snappy\",\"name\":\""
    "Snappy\"},{\"key\":\"sd_tone\",\"name\":\"Tone\"},{\"key\":\"sd_drive\",\"name\":\"Drive\"},{\"key\":\"sd_dist_type\",\"na"
    "me\":\"Distortion\"},{\"key\":\"sd_level\",\"name\":\"Level\"}]},\"lt\":{\"name\":\"Low Tom\",\"knobs\":[\"lt_tune\",\"lt_"
    "decay\",\"lt_drive\",\"lt_dist_type\",\"lt_level\"],\"params\":[{\"key\":\"lt_tune\",\"name\":\"Tune\"},{\"key\":\"lt_de"
    "cay\",\"name\":\"Decay\"},{\"key\":\"lt_drive\",\"name\":\"Drive\"},{\"key\":\"lt_dist_type\",\"name\":\"Distortion\"},{\""
    "key\":\"lt_level\",\"name\":\"Level\"}]},\"ht\":{\"name\":\"Hi Tom\",\"knobs\":[\"ht_tune\",\"ht_decay\",\"ht_drive\",\"ht"
    "_dist_type\",\"ht_level\"],\"params\":[{\"key\":\"ht_tune\",\"name\":\"Tune\"},{\"key\":\"ht_decay\",\"name\":\"Decay\"},"
    "{\"key\":\"ht_drive\",\"name\":\"Drive\"},{\"key\":\"ht_dist_type\",\"name\":\"Distortion\"},{\"key\":\"ht_level\",\"name"
    "\":\"Level\"}]},\"ch\":{\"name\":\"Closed Hat\",\"knobs\":[\"ch_tune\",\"ch_decay\",\"ch_drive\",\"ch_dist_type\",\"ch_l"
    "evel\",\"hh_choke\"],\"params\":[{\"key\":\"ch_tune\",\"name\":\"Tune\"},{\"key\":\"ch_decay\",\"name\":\"Decay\"},{\"key\""
    ":\"ch_drive\",\"name\":\"Drive\"},{\"key\":\"ch_dist_type\",\"name\":\"Distortion\"},{\"key\":\"ch_level\",\"name\":\"Lev"
    "el\"},{\"key\":\"hh_choke\",\"name\":\"Choke\"}]},\"oh\":{\"name\":\"Open Hat\",\"knobs\":[\"oh_tune\",\"oh_decay\",\"oh_d"
    "rive\",\"oh_dist_type\",\"oh_level\"],\"params\":[{\"key\":\"oh_tune\",\"name\":\"Tune\"},{\"key\":\"oh_decay\",\"name\":"
    "\"Decay\"},{\"key\":\"oh_drive\",\"name\":\"Drive\"},{\"key\":\"oh_dist_type\",\"name\":\"Distortion\"},{\"key\":\"oh_lev"
    "el\",\"name\":\"Level\"}]},\"cy\":{\"name\":\"Cymbal\",\"knobs\":[\"cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\","
    "\"cy_level\"],\"params\":[{\"key\":\"cy_tune\",\"name\":\"Tune\"},{\"key\":\"cy_decay\",\"name\":\"Decay\"},{\"key\":\"cy_d"
    "rive\",\"name\":\"Drive\"},{\"key\":\"cy_dist_type\",\"name\":\"Distortion\"},{\"key\":\"cy_level\",\"name\":\"Level\"}]}"
    ",\"cp\":{\"name\":\"Clap\",\"knobs\":[\"cp_tune\",\"cp_decay\",\"cp_noise\",\"cp_drive\",\"cp_dist_type\",\"cp_level\"],"
    "\"params\":[{\"key\":\"cp_tune\",\"name\":\"Tune\"},{\"key\":\"cp_decay\",\"name\":\"Decay\"},{\"key\":\"cp_noise\",\"name\""
    ":\"Noise\"},{\"key\":\"cp_drive\",\"name\":\"Drive\"},{\"key\":\"cp_dist_type\",\"name\":\"Distortion\"},{\"key\":\"cp_le"
    "vel\",\"name\":\"Level\"}]},\"root\":{\"name\":\"6W6\",\"knobs\":[\"master_dist\",\"master_drive\",\"volume\",\"accent\"]"
    ",\"params\":[{\"level\":\"bd\",\"label\":\"Bass Drum\"},{\"level\":\"sd\",\"label\":\"Snare\"},{\"level\":\"lt\",\"label\":\""
    "Low Tom\"},{\"level\":\"ht\",\"label\":\"Hi Tom\"},{\"level\":\"ch\",\"label\":\"Closed Hat\"},{\"level\":\"oh\",\"label\":"
    "\"Open Hat\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\"cp\",\"label\":\"Clap\"},{\"key\":\"master_dist\",\"name"
    "\":\"Master Dist\"},{\"key\":\"master_drive\",\"name\":\"Master Drive\"},{\"key\":\"volume\",\"name\":\"Volume\"},{\"key"
    "\":\"accent\",\"name\":\"Accent\"},{\"key\":\"hh_choke\",\"name\":\"Choke\"},{\"key\":\"note_map\",\"name\":\"Note Map\"}]}"
    "}}";

#endif /* SD606_PARAMS_H */
